# permissions for end users to view k3s.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: k3-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k3
    app.kubernetes.io/part-of: k3
    app.kubernetes.io/managed-by: kustomize
  name: k3-viewer-role
rules:
- apiGroups:
  - webapplication.abeni
  resources:
  - k3s
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapplication.abeni
  resources:
  - k3s/status
  verbs:
  - get
